name: CI Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/build/**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test

  generate_docs:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.10'

      - name: Install dependencies for docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build HTML documentation
        run: |
          cd docs
          make html

      - name: Commit and push updated docs
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add docs/build/html/index.html
          git commit -m "Update Sphinx documentation"
          git push
        continue-on-error: true

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ahmedamann/aseproject:latest .

      - name: Push Docker image
        run: docker push ahmedamann/aseproject:latest